### ISSUE TITLE
ConnectionResetError raised by WorkerMonitor

### ISSUE THREAD

**Issue by douglasppaz** [Ilhasoft/celery-worker-on-demand#4]
```

Exception in thread Thread-2:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner,
    self.run(),
  File "/root/src/celery-worker-on-demand/celery_worker_on_demand/__init__.py", line 124, in run,
    recv.capture(limit=None, timeout=None, wakeup=True),
  File "/usr/local/lib/python3.6/site-packages/celery/events/receiver.py", line 92, in capture,
    return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup)),
  File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume,
    conn.drain_events(timeout=safety_interval),
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 315, in drain_events,
    return self.transport.drain_events(self.connection, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events,
    return connection.drain_events(**kwargs),
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events,
    while not self.blocking_read(timeout):,
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 496, in blocking_read,
    frame = self.transport.read_frame(),
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 243, in read_frame,
    frame_header = read(7, True),
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 418, in _read,
    s = recv(n - len(rbuf)),
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by douglasppaz** [comment]
```
Exception in thread Thread-3:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner,
    self.run(),
  File "/root/src/celery-worker-on-demand/celery_worker_on_demand/__init__.py", line 140, in run,
    recv.capture(limit=None, timeout=None, wakeup=True),
  File "/usr/local/lib/python3.6/site-packages/celery/events/receiver.py", line 92, in capture,
    return list(self.consume(limit=limit, timeout=timeout, wakeup=wakeup)),
  File "/usr/local/lib/python3.6/site-packages/kombu/mixins.py", line 192, in consume,
    conn.drain_events(timeout=safety_interval),
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 315, in drain_events,
    return self.transport.drain_events(self.connection, **kwargs),
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 103, in drain_events,
    return connection.drain_events(**kwargs),
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events,
    while not self.blocking_read(timeout):,
  File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 496, in blocking_read,
    frame = self.transport.read_frame(),
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 243, in read_frame,
    frame_header = read(7, True),
  File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 418, in _read,
    s = recv(n - len(rbuf)),
ConnectionResetError: [Errno 104] Connection reset by peer
```
Caused by this line:
https://github.com/Ilhasoft/celery-worker-on-demand/blob/0.1.2/celery_worker_on_demand/__init__.py#L140
